package com.example.demo.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import lombok.RequiredArgsConstructor;

import com.example.demo.entity.User;
import com.example.demo.repository.UserRepository;
import com.example.demo.dto.auth.RegisterRequest;
import com.example.demo.dto.auth.LoginRequest;
import com.example.demo.dto.auth.TokenResponse;
import com.example.demo.security.JwtService;

@Service
@RequiredArgsConstructor
/**
 * Service responsible for authentication operations.
 *
 * Main concept:
 * - Exposes high-level authentication actions: register and login.
 * - Delegates persistence to `UserRepository`, handles password hashing and token generation.
 *
 * Responsibilities:
 * - `register`: validate uniqueness of email, hash the password with BCrypt, and save the user.
 * - `login`: verify credentials and return a JWT generated by `JwtService`.
 */
public class AuthService {

    private final UserRepository userRepository;
    private final JwtService jwtService;

    // local encoder instance; can be exposed as a @Bean if you prefer
    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

    @Transactional
    public TokenResponse register(RegisterRequest request) {
        userRepository.findByEmail(request.getEmail()).ifPresent(u -> {
            throw new IllegalArgumentException("Email already in use");
        });

        User user = User.builder()
                .name(request.getName())
                .email(request.getEmail())
                .password(passwordEncoder.encode(request.getPassword()))
                .role(request.getRole())
                .build();

        User saved = userRepository.save(user);
        String token = jwtService.generateToken(saved);
        return TokenResponse.builder().token(token).build();
    }

    public TokenResponse login(LoginRequest request) {
        User user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> new IllegalArgumentException("Invalid email or password"));

        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {
            throw new IllegalArgumentException("Invalid email or password");
        }

        String token = jwtService.generateToken(user);
        return TokenResponse.builder().token(token).build();
    }

}
