package com.example.demo.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import lombok.RequiredArgsConstructor;

import com.example.demo.entity.User;
import com.example.demo.repository.UserRepository;
import com.example.demo.dto.auth.RegisterRequest;
import com.example.demo.dto.auth.LoginRequest;
import com.example.demo.dto.auth.TokenResponse;
import com.example.demo.security.JwtUtils;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import java.util.List;

@Service
@RequiredArgsConstructor
/**
 * Service responsible for authentication operations.
 *
 * Main concept:
 * - Exposes high-level authentication actions: register and login.
 * - Delegates persistence to `UserRepository`, handles password hashing and token generation.
 *
 * Responsibilities:
 * - `register`: validate uniqueness of email, hash the password with BCrypt, and save the user.
 * - `login`: verify credentials and return a JWT generated by `JwtService`.
 */
public class AuthService {

    private final UserRepository userRepository;
    private final JwtUtils jwtUtils;

    // local encoder instance; can be exposed as a @Bean if you prefer
    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

    @Transactional
    public TokenResponse register(RegisterRequest request) {
        userRepository.findByEmail(request.getEmail()).ifPresent(u -> {
            throw new IllegalArgumentException("Email already in use");
        });

        User user = User.builder()
                .name(request.getName())
                .email(request.getEmail())
                .password(passwordEncoder.encode(request.getPassword()))
                .role(User.Role.USER)
                .build();

        User saved = userRepository.save(user);
        String token = jwtUtils.generateToken(toUserDetails(saved));
        return TokenResponse.builder()
            .token(token)
            .email(saved.getEmail())
            .name(saved.getName())
            .build();
    }

    public TokenResponse login(LoginRequest request) {
        User user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> new IllegalArgumentException("Invalid email or password"));

        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {
            throw new IllegalArgumentException("Invalid email or password");
        }

        String token = jwtUtils.generateToken(toUserDetails(user));
        return TokenResponse.builder()
            .token(token)
            .email(user.getEmail())
            .name(user.getName())
            .build();
    }

    /**
     * Convert application User entity to Spring Security UserDetails including authorities.
     */
    public UserDetails toUserDetails(User user) {
        String roleName = "ROLE_" + user.getRole().name();
        GrantedAuthority auth = new SimpleGrantedAuthority(roleName);
        return new org.springframework.security.core.userdetails.User(user.getEmail(), user.getPassword(), List.of(auth));
    }

}
